name: core
description: plugin

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  injectable: ^2.1.0
  get_storage: ^2.0.3
  flutter_svg: ^2.0.2
  cached_network_image: ^3.2.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.1.1


flutter:


  uses-material-design: true
  assets:
    - config/
    - assets/fonts/
